In [21]:
import torch
from torch.autograd import Variable
import numpy as np

xy = np.loadtxt('diabetes.csv', delimiter=',', dtype=np.float32)
x_data = Variable(torch.from_numpy(xy[:, 0:-1]))
y_data = Variable(torch.from_numpy(xy[:, [-1]]))

print(x_data.data.shape)
print(y_data.data.shape)


class Model(torch.nn.Module):

    def __init__(self):
       
        super(Model, self).__init__()
        self.l1 = torch.nn.Linear(8, 6)
        self.l2 = torch.nn.Linear(6, 4)
        self.l3 = torch.nn.Linear(4, 1)

        self.sigmoid = torch.nn.Sigmoid()

    def forward(self, x):
        
        out1 = self.sigmoid(self.l1(x))
        out2 = self.sigmoid(self.l2(out1))
        y_pred = self.sigmoid(self.l3(out2))
        return y_pred


model = Model()



criterion = torch.nn.BCELoss(size_average=True)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Training loop
for epoch in range(100):
        # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

  
    loss = criterion(y_pred, y_data)
    print(epoch, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

torch.Size([759, 8])
torch.Size([759, 1])
0 0.6900227665901184
1 0.6853911876678467
2 0.6812512278556824
3 0.6775501370429993
4 0.6742392182350159
5 0.6712766885757446
6 0.668624222278595
7 0.6662486791610718
8 0.6641209125518799
9 0.6622132062911987
10 0.6605024337768555
11 0.6589677929878235
12 0.6575902700424194
13 0.6563538312911987
14 0.6552429795265198
15 0.6542451977729797
16 0.6533478498458862
17 0.6525409817695618
18 0.6518154740333557
19 0.6511630415916443
20 0.6505750417709351
21 0.6500465869903564
22 0.6495700478553772
23 0.6491405367851257
24 0.6487540602684021
25 0.6484049558639526
26 0.6480908393859863
27 0.6478073000907898
28 0.6475521326065063
29 0.6473208665847778
30 0.6471126079559326
31 0.6469246745109558
32 0.6467548608779907
33 0.6466018557548523
34 0.64646315574646
35 0.6463384628295898
36 0.6462252140045166
37 0.6461225748062134
38 0.6460304856300354
39 0.6459470987319946
40 0.6458712220191956
41 0.6458028554916382
42 0.6457411050796509
43 0.6456849575042725
44 

In [22]:
outputs = model(x_data) 
print(outputs.data)
   

tensor([[ 0.6526],
        [ 0.6529],
        [ 0.6534],
        [ 0.6529],
        [ 0.6521],
        [ 0.6530],
        [ 0.6531],
        [ 0.6528],
        [ 0.6529],
        [ 0.6523],
        [ 0.6524],
        [ 0.6528],
        [ 0.6522],
        [ 0.6528],
        [ 0.6526],
        [ 0.6522],
        [ 0.6528],
        [ 0.6525],
        [ 0.6529],
        [ 0.6525],
        [ 0.6521],
        [ 0.6527],
        [ 0.6532],
        [ 0.6534],
        [ 0.6525],
        [ 0.6536],
        [ 0.6537],
        [ 0.6524],
        [ 0.6522],
        [ 0.6531],
        [ 0.6538],
        [ 0.6530],
        [ 0.6530],
        [ 0.6530],
        [ 0.6528],
        [ 0.6524],
        [ 0.6523],
        [ 0.6516],
        [ 0.6538],
        [ 0.6522],
        [ 0.6532],
        [ 0.6525],
        [ 0.6531],
        [ 0.6524],
        [ 0.6528],
        [ 0.6528],
        [ 0.6526],
        [ 0.6527],
        [ 0.6539],
        [ 0.6537],
        [ 0.6535],
        [ 0.6529],
        [ 0.

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.autograd import Variable

seq_length = 2
input_dim = 5
hidden_dim = 3
batch_size = 2
num_layers = 1

cell = nn.RNN(input_size = input_dim , hidden_size = hidden_dim , batch_first = True)
init_hidden = Variable(torch.randn(num_layers,batch_size,hidden_dim))
inputs = [[[1,0,0,0,0],[0,0,1,0,0]] , [ [0,1,1,0,0],[1,1,0,0,0] ] ]
inputs = Variable(torch.Tensor(inputs))

outputs,hidden = cell(inputs,init_hidden)

print(outputs)
print(hidden)


tensor([[[ 0.0645,  0.5259,  0.3984],
         [-0.5723, -0.1520,  0.3550]],

        [[-0.8736,  0.7260,  0.8774],
         [-0.5424,  0.7017,  0.8730]]])
tensor([[[-0.5723, -0.1520,  0.3550],
         [-0.5424,  0.7017,  0.8730]]])


In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.autograd import Variable


class Net (nn.Module):
    def __init__(self,input_dim,hidden_dim,seq_length,num_layers,batch_size):
        super(Net,self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.seq_length = seq_length
        self.num_layers = num_layers
        self.batch_size = batch_size
        self.rnn = nn.RNN(input_size = input_dim , hidden_size = hidden_dim , batch_first = True)
        
    def forward(self,x,hidden):
        #x = x.view(batch_size,seq_length,input_dim)
        outputs,hidden = self.rnn(x,hidden)
        #outputs = outputs.view(-1,self.hidden_dim)
        #fin_out = []
        #for m2d in outputs:
        #    tlis= []
        #    for lis in m2d:
        #        for ele in lis:
        #            if (ele == 1):
        #                tlis.append(lis.index(ele))
        #    fin_out.append(tlis)
                    
            
        return hidden,outputs
    
    def init_hidden(self):
        return Variable(torch.randn(self.num_layers,self.batch_size,self.hidden_dim))

net = Net(input_dim = 5,hidden_dim =5,seq_length =6,num_layers= 1,batch_size = 1)    
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(),lr = 0.1)

x_data = [[[1,0,0,0,0],[0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0]]]
y_data = [[ [0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],[0,0,0,0,1] ]]

x_data = Variable(torch.Tensor(x_data))
y_data = Variable(torch.LongTensor(y_data))
hidden = net.init_hidden()
for epoch in range(100):
    hidden,output = net(x_data,hidden)
    optimizer.zero_grad()
    loss = 0
    for m2d,ym2d in zip(output,y_data):
        for out,label in zip(m2d,ym2d):
            print(torch.Tensor(torch.nonzero(label.data).squeeze().item()))
            loss += criterion(out,torch.Tensor(torch.nonzero(label.data).squeeze().item()))
            
    loss.backward()
    optimizer.step()
    print("epoch :%d , loss : %.3f" % (epoch+1 ,loss.item() ))
print("Done")


    

            

tensor(1.00000e-45 *
       [ 1.4013])


RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [50]:
x_data = [[[1,0,0,0,0],[0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0]]]
y_data = [[ [0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],[0,0,0,0,1] ]]

x_data = Variable(torch.Tensor(x_data))
y_data = Variable(torch.LongTensor(y_data))
for m2d in y_data:
    for lis in m2d:
        print(lis.data)

tensor([ 0,  1,  0,  0,  0])
tensor([ 1,  0,  0,  0,  0])
tensor([ 0,  0,  1,  0,  0])
tensor([ 0,  0,  0,  1,  0])
tensor([ 0,  0,  0,  1,  0])
tensor([ 0,  0,  0,  0,  1])


In [11]:
import torch
import torch.nn as nn
rnn = nn.GRU(10,20,1,batch_first = True)
inp = torch.randn(3,5,10)
ho = torch.randn(1,3,20)
out,hn = rnn(inp,ho)
print(out.size())
ln = nn.Linear(20,10)
print(ln(hn).size())

torch.Size([3, 5, 20])
torch.Size([1, 3, 10])


In [8]:
rn = nn.RNN(10,20,batch_first =True)
inp = torch.randn(3,5,10)
ho = torch.randn(1,3,20)
out,hn = rn(inp,ho)
print(out.size())


torch.Size([3, 5, 20])
